### ISSUE TITLE
README.md update proposals for Pulsar newbies

### ISSUE THREAD

**Issue by kaja78** [datastax/snowflake-connector#1]
Hi,
I was testing Pulsar with your snowflake-connector. This was my first Pulsar exercise. So I am just summing up here some issues, that I was facing and which might be worth mentioning in README.

- Pulsar version dependency - the connector is not working with latest stable Pulsar version (2.8.1). You need to build Pulsar from master branch.
- For my first tests, I was using Pulsar CLI client to create testing messages with JSON content. The message content in Snowflake table was encoded using Base64 and I did not understand why. In the end I found out, that message schema matters (and value.converter class does not). The Pulsar CLI client creates messages with BINARY schema. Once I used Java client and set schema on Producer to JSON, everything start working. Still not sure here, but probably value.converter (and may be key.converter) kafkaConnectorConfigProperties has no effect, since Pulsar messages are converted to Kafka messages in `org.apache.pulsar.io.kafka.connect.KafkaConnectSink.toSinkRecord()` method. This is very confusing. If there are some required kafkaConnectorConfigProperties, which are effectively ignored - it should me mentioned in the doc.
- The configs.topic configuration property seems to be ignored as well. Created this bug: https://github.com/apache/pulsar/issues/12880 This should solve the topic to table name mapping issue.

Anyway after checking some source code, I was able to make the connector running. So thanks for your project!

**Comment by dlg99** [comment]
Thank you!
The connector needs Apache Pulsar 2.9+ or [Datastax Luna Streaming 2.8](https://github.com/datastax/pulsar/tree/2.8.0_ds) (relevant changes cherry-picked there).

I'll work on a better documentation; if you have a fix for https://github.com/apache/pulsar/issues/12880 I'll be happy to  review the PR (or I'll get to fixing it a little bit later).

regarding the schema, I used the following CLI commands:

```
Set retention for the namespace:

$ bin/pulsar-admin namespaces set-retention public/default -t -1 -s 100M

Set topic schema:

$ cat ~/schema_sf_js.json
{
    "type": "JSON",
    "schema": "{\"type\":\"record\",\"name\":\"SnowflakeTestSchema\",\"namespace\":\"com.foo\",\"fields\":[{\"name\":\"col1\",\"type\":[\"null\",\"string\"]},{\"name\":\"col2\",\"type\":[\"null\",\"string\"]}]}",
    "properties": {}
}

$ bin/pulsar-admin schemas upload --filename ~/schema_sf_js.json snowflake-test
```

and to send the messages:

```
$ cat ~/a.json
{"col1": "val1", "col2": "val2"}


$ bin/pulsar-client produce snowflake-test -f ~/a.json -n 200 -vs json:"{\"type\":\"record\",\"name\":\"SnowflakeTestSchema\",\"namespace\":\"com.foo\",\"fields\":[{\"name\":\"col1\",\"type\":[\"null\",\"string\"]},{\"name\":\"col2\",\"type\":[\"null\",\"string\"]}]}"
```

**Comment by kaja78** [comment]
@dig99 Thanks, I was not aware about the -vs option in pulsar client...

I created the PR: https://github.com/apache/pulsar/pull/12893

**Comment by dlg99** [comment]
Here is a short getting started guide: https://medium.com/building-the-open-data-stack/datastax-presents-snowflake-sink-connector-for-apache-pulsar-53629b196064
It is a bit late to help you but it I hope it will help someone else

**Comment by dlg99** [comment]
Added link to the blog post into the readme.
