### ISSUE TITLE
wrapping the kafka connector is dangerous

### ISSUE THREAD

**Issue by raphaelauv** [datastax/snowflake-connector#2]
The kafka connector is not at least once -> https://github.com/snowflakedb/snowflake-kafka-connector/issues/58

still recently they corrected new bugs about that -> https://github.com/snowflakedb/snowflake-kafka-connector/releases/tag/v1.6.0

```
Do not update committed offset(In memory) and eventually to Kafka if insertFiles has failed.
```

**Comment by dlg99** [comment]
Released https://github.com/datastax/snowflake-connector/releases/tag/snowflake-connector-0.1.1 with updated snowflake conenctor.
