### ISSUE TITLE
Error on trying to configure the connector

### ISSUE THREAD

**Issue by Agusioma** [datastax/snowflake-connector#6]
After maneuvers, I finally reached a dead end with one error log consistent, ```com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "secureConnectBundle" (class [org.apache.pulsar.io](http://org.apache.pulsar.io/).kafka.connect.PulsarKafkaConnectSinkConfig), not marked as ignorable```. There's nowhere that field is being set both in the UI and even when trying to use Pulsar-admin.

**Comment by nicoloboschi** [comment]
@Agusioma could you copy here your setup? specifically, the way you upload the sink and the sink configuration file

`secureConnectBundle` seems related to Cassandra/Astra DB

**Comment by Agusioma** [comment]
I used the UI and filled the configs to the inputs. And this was the autogenerated config: 
```{
  "archive": "builtin://snowflake",
  "autoAck": true,
  "className": "com.datastax.oss.snowflake.SnowflakeSink",
  "cleanupSubscription": false,
  "configs": {
    "batchSize": "2",
    "kafkaConnectorConfigProperties": {
      "buffer.count.records": "10000",
      "buffer.flush.time": "60",
      "buffer.size.bytes": "5000000",
      "connector.class": "com.snowflake.kafka.connector.SnowflakeSinkConnector",
      "key.converter": "org.apache.kafka.connect.storage.StringConverter",
      "name": "tester",
      "snowflake.database.name": "TEST",
      "snowflake.private.key": "deleted the private key",
      "snowflake.schema.name": "TEST",
      "snowflake.url.name": "https://ektwpcf-bd52246.snowflakecomputing.com",
      "snowflake.user.name": "INCOGNITO",
      "tasks.max": "1000",
      "topics": "taa-tp",
      "value.converter": "com.snowflake.kafka.connector.records.SnowflakeJsonConverter"
    },
    "lingerTimeMs": "9998",
    "offsetStorageTopic": "taa-tp",
    "secureConnectBundle": "https://datastax-cluster-config-prod.s3.us-east-2.amazonaws.com/de227d8a-b179-4c3f-b613-58ceffae67fe-1/secure-connect-testdb.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2QRQ76S2JCB77W%2F20230207%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20230207T111424Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=a8c0ebdc148847587e7353cd20ff0a96d64a83fd34cc01a7cbefdcaf3a84a467",
    "topic": "taa-tp"
  },
  "customRuntimeOptions": "internal_data",
  "deadLetterTopic": null,
  "inputSpecs": {
    "persistent://taa-tenant/taa-ns/taa-tp": {
      "consumerProperties": {},
      "cryptoConfig": null,
      "poolMessages": false,
      "receiverQueueSize": null,
      "regexPattern": false,
      "schemaProperties": {},
      "schemaType": null,
      "serdeClassName": null
    }
  },
  "inputs": [
    "persistent://taa-tenant/taa-ns/taa-tp"
  ],
  "maxMessageRetries": null,
  "name": "test90",
  "namespace": "taa-ns",
  "negativeAckRedeliveryDelayMs": null,
  "parallelism": 1,
  "processingGuarantees": "EFFECTIVELY_ONCE",
  "resources": {
    "cpu": 0.25,
    "disk": 1000000000,
    "ram": 1000000000
  },
  "retainKeyOrdering": false,
  "retainOrdering": true,
  "runtimeFlags": null,
  "secrets": null,
  "sourceSubscriptionName": null,
  "sourceSubscriptionPosition": "Latest",
  "tenant": "taa-tenant",
  "timeoutMs": 5000,
  "topicToSchemaProperties": null,
  "topicToSchemaType": null,
  "topicToSerdeClassName": null,
  "topicsPattern": null,
  "transformFunction": null,
  "transformFunctionClassName": null,
  "transformFunctionConfig": null
} ```

**Comment by Agusioma** [comment]
And @nicoloboschi, just curious. Where can I raise issues connected to the Pulsar functions on Astra Streaming. I again used the UI to upload the functions.

**Comment by nicoloboschi** [comment]
```{
  "archive": "builtin://snowflake",
  "autoAck": true,
  "className": "com.datastax.oss.snowflake.SnowflakeSink",
  "cleanupSubscription": false,
  "configs": {
    "batchSize": "2",
    "kafkaConnectorConfigProperties": {
      "buffer.count.records": "10000",
      "buffer.flush.time": "60",
      "buffer.size.bytes": "5000000",
      "connector.class": "com.snowflake.kafka.connector.SnowflakeSinkConnector",
      "key.converter": "org.apache.kafka.connect.storage.StringConverter",
      "name": "tester",
      "snowflake.database.name": "TEST",
      "snowflake.private.key": "deleted the private key",
      "snowflake.schema.name": "TEST",
      "snowflake.url.name": "https://ektwpcf-bd52246.snowflakecomputing.com",
      "snowflake.user.name": "INCOGNITO",
      "tasks.max": "1000",
      "topics": "taa-tp",
      "value.converter": "com.snowflake.kafka.connector.records.SnowflakeJsonConverter"
    },
    "lingerTimeMs": "9998",
    "offsetStorageTopic": "taa-tp",
>>>>>>>    "secureConnectBundle": "https://datastax-cluster-config-prod.s3.us-east-2.amazonaws.com/de227d8a-b179-4c3f-b613-58ceffae67fe-1/secure-connect-testdb.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2QRQ76S2JCB77W%2F20230207%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20230207T111424Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=a8c0ebdc148847587e7353cd20ff0a96d64a83fd34cc01a7cbefdcaf3a84a467",
    "topic": "taa-tp"
  },
  "customRuntimeOptions": "internal_data",
  "deadLetterTopic": null,
  "inputSpecs": {
    "persistent://taa-tenant/taa-ns/taa-tp": {
      "consumerProperties": {},
      "cryptoConfig": null,
      "poolMessages": false,
      "receiverQueueSize": null,
      "regexPattern": false,
      "schemaProperties": {},
      "schemaType": null,
      "serdeClassName": null
    }
  },
  "inputs": [
    "persistent://taa-tenant/taa-ns/taa-tp"
  ],
  "maxMessageRetries": null,
  "name": "test90",
  "namespace": "taa-ns",
  "negativeAckRedeliveryDelayMs": null,
  "parallelism": 1,
  "processingGuarantees": "EFFECTIVELY_ONCE",
  "resources": {
    "cpu": 0.25,
    "disk": 1000000000,
    "ram": 1000000000
  },
  "retainKeyOrdering": false,
  "retainOrdering": true,
  "runtimeFlags": null,
  "secrets": null,
  "sourceSubscriptionName": null,
  "sourceSubscriptionPosition": "Latest",
  "tenant": "taa-tenant",
  "timeoutMs": 5000,
  "topicToSchemaProperties": null,
  "topicToSchemaType": null,
  "topicToSerdeClassName": null,
  "topicsPattern": null,
  "transformFunction": null,
  "transformFunctionClassName": null,
  "transformFunctionConfig": null
} ```

I've highlighted the `secureConnectBundle` option, please try to remove it.

**Comment by Agusioma** [comment]
> ```
>   "archive": "builtin://snowflake",
>   "autoAck": true,
>   "className": "com.datastax.oss.snowflake.SnowflakeSink",
>   "cleanupSubscription": false,
>   "configs": {
>     "batchSize": "2",
>     "kafkaConnectorConfigProperties": {
>       "buffer.count.records": "10000",
>       "buffer.flush.time": "60",
>       "buffer.size.bytes": "5000000",
>       "connector.class": "com.snowflake.kafka.connector.SnowflakeSinkConnector",
>       "key.converter": "org.apache.kafka.connect.storage.StringConverter",
>       "name": "tester",
>       "snowflake.database.name": "TEST",
>       "snowflake.private.key": "deleted the private key",
>       "snowflake.schema.name": "TEST",
>       "snowflake.url.name": "https://ektwpcf-bd52246.snowflakecomputing.com",
>       "snowflake.user.name": "INCOGNITO",
>       "tasks.max": "1000",
>       "topics": "taa-tp",
>       "value.converter": "com.snowflake.kafka.connector.records.SnowflakeJsonConverter"
>     },
>     "lingerTimeMs": "9998",
>     "offsetStorageTopic": "taa-tp",
> >>>>>>>    "secureConnectBundle": "https://datastax-cluster-config-prod.s3.us-east-2.amazonaws.com/de227d8a-b179-4c3f-b613-58ceffae67fe-1/secure-connect-testdb.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA2QRQ76S2JCB77W%2F20230207%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Date=20230207T111424Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=a8c0ebdc148847587e7353cd20ff0a96d64a83fd34cc01a7cbefdcaf3a84a467",
>     "topic": "taa-tp"
>   },
>   "customRuntimeOptions": "internal_data",
>   "deadLetterTopic": null,
>   "inputSpecs": {
>     "persistent://taa-tenant/taa-ns/taa-tp": {
>       "consumerProperties": {},
>       "cryptoConfig": null,
>       "poolMessages": false,
>       "receiverQueueSize": null,
>       "regexPattern": false,
>       "schemaProperties": {},
>       "schemaType": null,
>       "serdeClassName": null
>     }
>   },
>   "inputs": [
>     "persistent://taa-tenant/taa-ns/taa-tp"
>   ],
>   "maxMessageRetries": null,
>   "name": "test90",
>   "namespace": "taa-ns",
>   "negativeAckRedeliveryDelayMs": null,
>   "parallelism": 1,
>   "processingGuarantees": "EFFECTIVELY_ONCE",
>   "resources": {
>     "cpu": 0.25,
>     "disk": 1000000000,
>     "ram": 1000000000
>   },
>   "retainKeyOrdering": false,
>   "retainOrdering": true,
>   "runtimeFlags": null,
>   "secrets": null,
>   "sourceSubscriptionName": null,
>   "sourceSubscriptionPosition": "Latest",
>   "tenant": "taa-tenant",
>   "timeoutMs": 5000,
>   "topicToSchemaProperties": null,
>   "topicToSchemaType": null,
>   "topicToSerdeClassName": null,
>   "topicsPattern": null,
>   "transformFunction": null,
>   "transformFunctionClassName": null,
>   "transformFunctionConfig": null
> } 
> ```
> 
> I've highlighted the `secureConnectBundle` option, please try to remove it.

OK. I will try to write a custom config without the UI because it is uneditable there. Thank you @nicoloboschi
